name: ci
on:
  push:
    branches: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
           ref: ${{ github.event.pull_request.head.ref }}
      - uses: TimonVS/pr-labeler-action@v5.0.0
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v13
        with:
          name: cachix-action
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Tests
        run: nix develop -c go test -v ./... -test.short
      - name: Formatter
        run: nix develop -c go fmt ./... || true
      - name: Linter
        run: nix develop -c golangci-lint run || true
      - name: Build
        run: nix develop -c go build
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Run formatter/linter
