name: Draft a release

on:
  push:
    branches:
      - 'main'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:      
      - name: Update release draft
        id: draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: workflows/config/release-drafter.yml
